name: Android Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build APK
        run: |
          ./gradlew bundleRelease
        working-directory: /app

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: /app/build/outputs/bundle/release/*.aab

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: release-artifacts
          path: /app/build/outputs/bundle/release/

      - name: Create release ZIP
        run: |
          cd /app/build/outputs/bundle/release/
          zip -r release.zip *.aab
        working-directory: /app/build/outputs/bundle/release/

      - name: Upload release ZIP
        uses: actions/upload-artifact@v2
        with:
          name: release-zip
          path: /app/build/outputs/bundle/release/release.zip
