name: Build APK

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build APK
        run: |
          ./gradlew assembleRelease
        working-directory: your/project/directory

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: your/project/directory/app/build/outputs/apk/release/*.apk
